### PR TITLE
Fix buck build buck

### PR DESCRIPTION
**Pull request by tgummerer**
Summary:
buck build buck was broken by b50c6d26b8 ("Load
TranslatingJavacPhaseTracer from resources"), with the following error
message:
/home/tommy/work/buck/src/com/facebook/buck/java/Jsr199Javac.java:171: error: cannot access com.facebook.buck.java.tracing.JavacPhaseTracer
      TranslatingJavacPhaseTracer.setupTracing(
                                 ^
  class file for com.facebook.buck.java.tracing.JavacPhaseTracer not found
Errors: 1. Warnings: 1.

This is because of a missing dependency.  Add the dependency to fix the
build.

Test plan:
Check that buck build buck compiles buck successfully.

### CODE REVIEW

**Comment by sdwilsh** [comment]
We've got an internal change that I need to push out for this too.  This is a Java 8-only bug.

**Comment by sdwilsh** [comment]
Thanks for reporting this, however :)

**Comment by tgummerer** [comment]
@sdwilsh Ah ok thanks, I suspected it was something about my system.
