### ISSUE TITLE
previously-valid BUCK file not accepted anymore

### ISSUE THREAD

**Issue by jvillard** [facebook/buck#697]
hi all, I'm getting the following error with buck's latest master (see facebook/infer#296):

```
BUILD FAILED: Couldn't get dependency '//infer/tests/endtoend/java/comparison:comparison' of target '//infer/tests/endtoend:java_endtoend_tests':
Parse error for build file /Users/cruz/dev/infer/infer/tests/endtoend/java/comparison/BUCK: Stream closed
```

The BUCK file in question: https://github.com/facebook/infer/blob/master/infer/tests/endtoend/java/comparison/BUCK

Steps to reproduce:

```
git clone https://github.com/facebook/buck.git
cd buck/
ant && ./bin/buck --help
cd ..
git clone  https://github.com/facebook/infer.git
cd infer/
./autogen.sh && ./configure --disable-ocaml-annot --disable-ocaml-bin-annot --disable-c-analyzers && make -j
make test
```

This also repros with, eg, buck version v2016.01.18.01, although with a different error:

```
BUILD FAILED: Couldn't get dependency '//infer/tests/codetoanalyze/java/infer:tracing' of target '//infer/tests/endtoend/java/comparison:comparison':
Parse error for build file /home/jul/code/infer/infer/tests/codetoanalyze/java/infer/BUCK:   File "/home/jul/code/infer/infer/tests/codetoanalyze/java/infer/BUCK", line 46, in <module>
    'PUBLIC',
  File "/home/jul/code/infer/buck-out/tmp/buck_run.kqKk2x/buck1773497332593288439.py", line 119, in invoke
    return self.func(*args, **updated_kwargs)
TypeError: genrule() got an unexpected keyword argument 'deps'
```

On the other hand, v2015.10.05.01 works fine.

A git bisect points to this commit as a candidate culprit: d2c6edbf7b41ee5662902c1f06f570fa4bc8e005

I used this command for the bisect, marking commits as bad when buck itself was failing to run the tests (sometimes the tests were failing, but I didn't investigate further why and marked those as good, so my bisect should be taken with a grain of salt):

```sh
#!/bin/sh

ant clean
ant
./bin/buck --help || true
cd ~/code/infer
rm -fr buck-out
PATH=$HOME/code/infer/infer/bin:$HOME/code/buck/bin:$PATH make -j4 test
```

**Comment by Coneko** [comment]
I can see there are several `genrule` targets that have `deps` defined. That attribute was removed, so you're going to have to remove it to use a newer version of Buck.

https://github.com/facebook/infer/blob/0db83eb5dd5ebe097edb435cfc21050d43081462/infer/tests/codetoanalyze/java/eradicate/BUCK#L39
https://github.com/facebook/infer/blob/6389cb9bd0c47b21c72a2aa3532d0301ddb218fc/infer/tests/codetoanalyze/java/checkers/BUCK#L35
https://github.com/facebook/infer/blob/0db83eb5dd5ebe097edb435cfc21050d43081462/infer/tests/codetoanalyze/java/tracing/BUCK#L33
https://github.com/facebook/infer/blob/6d91199be7dab5c70d7ba874e776dee8c95e8b7d/infer/tests/codetoanalyze/c/errors/BUCK#L20
https://github.com/facebook/infer/blob/0db83eb5dd5ebe097edb435cfc21050d43081462/infer/tests/codetoanalyze/java/infer/BUCK#L50
https://github.com/facebook/infer/blob/0db83eb5dd5ebe097edb435cfc21050d43081462/infer/tests/codetoanalyze/java/infer/BUCK#L39
