### ISSUE TITLE
SwiftCompile should include headers if bridging header is presented

### ISSUE THREAD

**Issue by fkorotkov** [facebook/buck#909]
It seems when a bridging header is presented header symlink trees should be provided to swift compiler via `-I` flag.

I've created an example here: https://github.com/fkorotkov/buck-sandbox/commit/46d25d39a07f52f3e2f981d080c1eef0845ca26d

Basically my bridging header **next to a BUCK** file has `#import "objc/Foo.h"` and _objc/Foo.h_ contains `#import "Version.h"` where _Version.h_ suppose to be next to the BUCK file as well. With  this special setup I'm getting:

```
complex_objc_swift/Foo-Bridging-Header.h:1:
#import "objc/Foo.h"
        ^
/Users/fedor_korotkov/workspace/buck-sandbox/complex_objc_swift/objc/Foo.h:3:9: error: 'Version.h' file not found
#import "Version.h"
        ^
<unknown>:0: error: failed to import bridging header 'complex_objc_swift/Foo-Bridging-Header.h'
```

I was able to fix the command line by adding `-I complex_objc_swift`.

**Comment by nguyentruongtho** [comment]
This really confuses me, or it looks like a bad practice imho, since if you are right about it, by looking at `objc/Foo.h` itself, you have no idea of where `Version.h` is located.

**Comment by fkorotkov** [comment]
@nguyentruongtho agreed on a bad example structure. I've moved `Version.h` to `objc/version` folder and `#import "version/Version.h"` or `#import "Bridging/Version.h"` are still failing(https://github.com/fkorotkov/buck-sandbox/commit/c486eea6d34a2bb3717b206842d8fb0513df6835).

**Comment by fkorotkov** [comment]
Actually after deleting `buck-out` `#import "Bridging/Version.h"` works. But should `version/Version.h` work as well?

**Comment by dinhviethoa** [comment]
@ryu2 what do you think?

**Comment by fkorotkov** [comment]
Also a disclaimer: I have experience with different build systems like Pants and Blaze but not so much with iOS. That's why my iOS related questions in the beginning might be stupid. :-) But I'm learning quick! 😅

**Comment by ryu2** [comment]
We should already support including the symlink trees.  Does it work if you include the bridging header in the `exported_headers`?

**Comment by fkorotkov** [comment]
@ryu2 it works! I thought I don't need to include it but now it make sense! Will try on my big app and report back. Thanks a lot!

BTW I noticed that in the resulting cmd the bridging header is passed like `-import-objc-header complex_objc_swift/Foo-Bridging-Header.h`. Should it use a symlink one instead though? https://github.com/facebook/buck/blob/master/src/com/facebook/buck/swift/SwiftCompile.java#L149

**Comment by fkorotkov** [comment]
@ryu2 it's weird but after nuking `build-out` it stopped working. I did some further investigation and came up with a workaround: https://github.com/fkorotkov/buck/commit/58096d0367391cc08fda3f0d773442c170614846

It fixed my issue on the small example and it also works on my app. What do you think? If it makes sense I'll add some tests and submit a PR.

Seems Buck includes symlink trees of deps but not of the target itself.

**Comment by ryu2** [comment]
@fkorotkov Thanks, that sounds like the right fix.  Feel free to submit a PR.
